// front-end/angular/my-first-app/src/app/components/card/card.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-card',
  templateUrl: './card.component.html',
  styleUrls: ['./card.component.css']
})
export class CardComponent implements OnInit {

  @Input('title') caption = ''

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="card" style="width: 18rem;">
    <img src="https://via.placeholder.com/150" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">{{caption}}</h5>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
  </div>

// front-end/react/my-first-app/src/Card.js
import React from 'react'
import './Card.css'

export default function Card() {

    const cardStyle = {width: '18rem'}

  return (
    <div className="card" style={cardStyle}>
    <img src="https://picsum.photos/200" className="card-img-top" alt="..."/>
    <div className="card-body">
        <h5 className="card-title">Card title</h5>
        <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" className="btn btn-primary">Go somewhere</a>
    </div>
    </div>
  )
}
