// front-end/angular/my-first-app/src/app/components/badge.component.ts
import { Component, Input } from "@angular/core";

@Component({
    selector: 'app-badge',
    templateUrl: './badge.component.html'
})
export class BadgeComponent{
    // fields
    count: number = 0
    @Input('caption') caption : string = 'Inbox'

    // methods
    incrementCount(){
        console.log(this.count)
        this.count++;
    }

}
<button (click)="incrementCount()" type="button" class="btn btn-primary">
    {{caption}} <span class="badge bg-secondary">{{count}}</span>
</button>

// front-end/react/my-second-app/src/components/Badge.js
import React, {useState} from 'react'

export default function Badge(props) {

  const [count, setCount] = useState(0)

  const handleClick = () => {
      console.log('click event');
    //   props.caption = "Something"
    setCount(count + 1);
  }

  return (
    <button type="button" onClick={handleClick} className="btn btn-primary">
    {props.caption} <span className="badge bg-secondary">{count}</span>
    </button>
  )
}
