// front-end/react/my-second-app/src/App.js

import './App.css';
import AddEmployee from './components/AddEmployee';
import Badge from './components/Badge';
import Dropdown from './components/Dropdown';
import ViewEmployees from './components/ViewEmployees';
import React, {useState} from 'react'
import BadgeWithClass from './components/BadgeWithClass';
import ViewEmployeesWithClass from './components/ViewEmployeesWithClass';

function App() {

  // useState --- 
  const [employees, setEmployees] = useState([
    {firstName: "Ravi", lastName: 'Sharma', salary: 66666},
    {firstName: "Harshit", lastName: "Tomar", salary: 34434}

  ])

  const addEmployee = (emp) => {
    console.log('In parent...');
    console.log(emp)
    setEmployees([...employees, emp])
  }

  return (
    <div>
      <Badge caption="Votes"/>
      <BadgeWithClass caption="Votes"/>
      <ViewEmployees employees={employees}/>
      <hr/>
      <ViewEmployeesWithClass employees={employees}/>
      {/* <Badge caption="Votes"/>
      <Dropdown label="Select Courses" /> */}
      {/* <ViewEmployees employees={employees}/>
      <AddEmployee whenEmployeeAdded={addEmployee}/> */}
    </div>
  );
}

export default App;

// front-end/angular/my-first-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { Employee } from './employee';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title: string = 'React';
  employees: Array<Employee> = [
    {firstName: "Ravi", lastName: 'Sharma', salary: 66666},
    {firstName: "Harshit", lastName: "Tomar", salary: 34434}
  ]


}

<div class="container">
    <div class="row">
    <!-- <h2>View Employees</h2> -->
    <!-- <app-card title="{{title}}"></app-card> -->
    <app-card [title]="title"></app-card>
    <!-- <app-message></app-message>
    <app-badge caption="Sent"></app-badge>
    <app-badge caption="Spam"></app-badge> -->
    <app-view-employees [employees]="employees"></app-view-employees>
</div>
</div>
