// front-end/react/my-second-app/src/components/Dropdown.js
import React, {useState} from 'react'

export default function Dropdown(props) {


  // way to set state....  
  const [show, setShow] = useState(false); 
  const [courses, setCourses] = useState([
      'React', 'Angular', 'NodeJS', 'Test'
  ])
  // changing the state... show->true->false
  const toggleShow = () => {
        setShow(!show);
        console.log(show);
  }

  let coursesList = courses.map((course, i) => <li><a className="dropdown-item" href="#">{course}</a></li>);
  console.log(coursesList);

  return (
    <div className="dropdown">
  <button onClick={toggleShow} className="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    {props.label}
  </button>
  <ul className={show?'dropdown-menu show': 'dropdown-menu'} aria-labelledby="dropdownMenuButton1">
     {coursesList}
  </ul>
</div>
  )
}

// front-end/angular/my-first-app/src/app/components/dropdown/dropdown.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-dropdown',
  templateUrl: './dropdown.component.html',
  styleUrls: ['./dropdown.component.css']
})
export class DropdownComponent implements OnInit {

  show: boolean = false;
  items: Array<string> = ['Item1', 'Item2', 'Item3']
  item: string = 'Select Items'

  toggleShow(){
    this.show = !this.show;
  }

  handleItemSelect(item: string){
    console.log('In parent: item selected by child ', item);
    this.item = item;
    this.show = false;
  }

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="dropdown">
    <button (click)="toggleShow()" class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
      {{item}}
    </button>
    <ul [ngClass]="show? 'dropdown-menu show' : 'dropdown-menu' " aria-labelledby="dropdownMenuButton1">
      <app-dropdown-item *ngFor="let item of items" [item]="item" (itemSelect)="handleItemSelect($event)"></app-dropdown-item>
    </ul>
  </div>
